config/routes.rb
Rails.application.routes.draw do
  get '/incidents/news' => 'incidents#news'

  resources :incidents

  root 'incidents#index'

end

app/models/incident.rb
class Incident < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/incidents_controller.rb
class IncidentsController < ApplicationController
  before_action :set_incident, only: [:show, :edit, :update, :destroy]
  # layout :false

  # GET /incidents
  # GET /incidents.json
  def index
    @incidents = Incident.all
    respond_to do |format|
      format.html { }
      format.xml {
        render :text=>@incidents.to_xml(root:"data")
        }
    end
  end

  def news
    @incidents = Incident.where("updated_at < ?", Time.now.yesterday)
    render xml: @incidents
  end

  # GET /incidents/1
  # GET /incidents/1.json
  def show
    @incident = Incident.find(params[:id])
    respond_to do |format|
      format.js { }
      # format.html {
      #   render partial: "show", locals: {incident: @incident}
      # }
      # format.xml {
      #   render xml: @incident.to_xml(only:[:latitude, :longitude, :title, :description], root: "data" )
      # }
    end
  end


  # GET /incidents/new
  def new
    @incident = Incident.new
    respond_to do |format|
      format.html {
        @incident.latitude = params[:latitude]
        @incident.longitude = params[:longitude]
        render partial: "new", locals: { incident: @incident}
      }

      format.xml {
        render xml: @incident.to_xml(only:[:latitude, :longitude, :title, :description], root: "data" )
      }
    end
  end

  # GET /incidents/1/edit
  def edit
    @incident = Incident.find(params[:id])
    respond_to do |format|
      format.js {  }

    end
  end

  # POST /incidents
  # POST /incidents.json
  def create
    @incident = Incident.new(incident_params)

    respond_to do |format|
      if @incident.save
        flash[:notice] = 'Incident was successfully created.'
        format.js { }
        # format.xml {render xml: @incident, status: :created, location: @incident }
        # format.html { redirect_to @incident, notice: 'Incident was successfully created.' }
        # format.json { render :show, status: :created, location: @incident }
      else
        format.html { render :new }
        format.json { render json: @incident.errors, status: :unprocessable_entity }
        format.xml {render xml: @incident.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /incidents/1
  # PATCH/PUT /incidents/1.json
  def update
    respond_to do |format|
      if @incident.update(incident_params)
        flash[:notice] = 'Incident was successfully created.'
        format.js { }
        format.html { redirect_to @incident, notice: 'Incident was successfully updated.' }
        format.json { render :show, status: :ok, location: @incident }
      else
        format.html { render :edit }
        format.json { render json: @incident.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /incidents/1
  # DELETE /incidents/1.json
  def destroy
    @incident.destroy
    respond_to do |format|
      format.html { redirect_to incidents_url, notice: 'Incident was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_incident
      @incident = Incident.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def incident_params
      params.require(:incident).permit(:mountain, :latitude, :longitude, :when, :title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/incidents_helper.rb
module IncidentsHelper
end

app/views/incidents/_edit.html.haml
%h1 Edit Incident
= render partial: "my", locals: {incident: @incident}

app/views/incidents/_form.html.haml
= form_for(@incident) do |f|
  - if @incident.errors.any?
    #error_explanation
      %h2
        = pluralize(@incident.errors.count, "error")
        prohibited this incident from being saved:
      %ul
        - @incident.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :mountain
    %br/
    = f.text_field :mountain
  .field
    = f.label :latitude
    %br/
    = f.text_field :latitude
  .field
    = f.label :longitude
    %br/
    = f.text_field :longitude
  .field
    = f.label :when
    %br/
    = f.datetime_select :when
  .field
    = f.label :title
    %br/
    = f.text_field :title
  .field
    = f.label :description
    %br/
    = f.text_area :description
  .actions
    = f.submit

app/views/incidents/_map.html.erb
<%
  google_key='ABQIAAAAnfs7bKE82qgb3Zc2YyS-oBT2yXp_' +
    'ZAY8_ufC3CFXhHIE1NvwkxSySz_REpPq-4WZA27OwgbtyR3VcA'
  full_page ||= true
  show_action ||= 'show'
  new_action ||= 'new'
  data ||= nil
%>
<div id="map"
  align="right"
  style="border: 1px solid #979797;
     min-width: 400px;
<%     if full_page -%>
     min-height: 800px;
     height: 800px;
<%     else -%>
     min-height: 400px;
     height: 400px;
<%     end -%>
"></div>
<script
  src="http://maps.google.com/maps?file=api&v=2&key=<%= google_key %>"
  type="text/javascript"></script>
<script type="text/javascript">
  var map_location = new GLatLng(0, 0);
  var map;
  // console.log(map)
  function show_path(id) {

    var show_path = "<%= url_for(:controller=>controller.controller_name, :action=>show_action, :id=>'REPLACEME') %>";
    return show_path.replace("REPLACEME", id);

  }

  function new_path() {

    return "<%= url_for(:controller=>controller.controller_name, :action=>new_action) %>";
  }

  function createMarker(point, label, html, id) {
    var mark1 = new GMarker(point);
    // console.log(mark1)
    mark1.enableDragging();
    mark1.bouncy = true;
    GEvent.addListener(mark1, "click",
      function() {
        map_location = mark1.getPoint();
        map.panTo(map_location);
        var link = "";
        if (id != "") {
       <% if show_action != nil %>
            link = show_path(id);
            // console.log("show_action : " + link)
            new Ajax.Request(link, {
              method: 'get',
              onSuccess: function(transport) {
                var html = "<div align='left' id='map_info' style='min-width: 400px; min-height: 300px; width: 400px; height: 300px;'>" +
                  transport.responseText + "</div>";
                mark1.openInfoWindowHtml(html);
              }
            });
       <% else %>
            link = "<br/><a href='/incidents/" + id + "'>More...</a>";
            mark1.openInfoWindowHtml("<div align='left'><strong>" + label + "</strong><br/>"
              + html + link + "</div>");
       <% end %>
        } else {
          mark1.openInfoWindowHtml("<div align='left'><strong>" + label + "</strong><br/>"
            + html + link + "</div>");
        }
      }
    );
    return mark1;
  }

 function initialize() {

   if (GBrowserIsCompatible()) {
     map = new GMap2(document.getElementById("map"));
     map.setCenter(map_location, 16);
     map.setZoom(2);
     map.addControl(new GLargeMapControl());
     map.addControl(new GHierarchicalMapTypeControl());
     map.enableScrollWheelZoom();
     map.enableDoubleClickZoom();
     map.setMapType(G_HYBRID_MAP);
   }
 }

 function textFor(element, tag) {
   return element.getElementsByTagName(tag)[0].firstChild.nodeValue;
 }


 function addPoints(points) {
   var totlat = 0.0;
   var totlon = 0.0;
   var avcount = 0;
   for (var i = 0; i < points.length; i++) {
     m = points[i];
     // obtain the attribues of each marker
     var lat = parseFloat(textFor(m, "latitude"));
     var lng = parseFloat(textFor(m, "longitude"));
     totlat = totlat + lat;
     totlon = totlon + lng;
     avcount = avcount + 1;
     var point = new GLatLng(lat,lng);
     var html = textFor(m, "description");
     var label = textFor(m, "title");
     // create the marker
     var id ="";
     if (points.length > 1) {
       id = textFor(m, "id");
     }
     var marker = createMarker(point,label,html, id);
     map.addOverlay(marker);
   }
   return new GLatLng(totlat / avcount, totlon / avcount);
 }

 function loadXml(url) {
   var request = GXmlHttp.create();
   request.open("GET", url, true);
   request.onreadystatechange = function() {
     if (request.readyState == 4) {
       var xmlDoc = GXml.parse(request.responseText);
       var points = new Array();
       points[0] = xmlDoc.documentElement;
       var multi = (points[0].getElementsByTagName("datum").length > 0);
       if (multi) {
         points=points[0].getElementsByTagName("datum");
       }
       center = addPoints(points);
       map.setCenter(center);
       if (multi) {
         map.setZoom(2);
       } else {
         map.setZoom(8);
       }
     }
   }
   request.send(null);
 }
 initialize();
<% if new_action != nil -%>

   GEvent.addListener(map, 'click',
     function(overlay, point) {
       // console.log(point)
       if (point) {
         var marker = new GMarker(point);
         marker.enableDragging();
         marker.bouncy = true;
         var info = null;
          // console.log(marker)
         GEvent.addListener(marker, "infowindowbeforeclose",
           function() {
             info = document.getElementById("map_info");
           }
         );

         GEvent.addListener(marker, "infowindowclose",
           function() {
             if (info != null) {
               GEvent.addListener(marker, "click",
                 function() {
                 map_location = marker.getPoint();
                 map.panTo(map_location);
                 marker.openInfoWindowHtml(info);
                 console.log(info)
               });
             }
           }
         );
         map.addOverlay(marker);
         var params = {}
         // console.log(point.k)
         params["latitude"] = point.k
         params["longitude"] = point.B

         new Ajax.Request(new_path(), {
           method: 'get',
           parameters: params,
           onSuccess: function(transport) {
             var html = "<div align='left' id='map_info' style='min-width: 400px; min-height: 300px; width: 400px; height: 300px;'>" +
               transport.responseText + "</div>";
             marker.openInfoWindowHtml(html);
           }
         });
       }
     }
   );
<%
  end
  if (data != nil) -%>
  loadXml('<%= data -%>');
<%  end %>

</script>

app/views/incidents/_my.html.haml
= form_for incident, remote: true do |f|
  %p
    = f.label  :mountain
    = f.text_field :mountain
  - if params[:action] == "new"
    = f.hidden_field :latitude
    = f.hidden_field :longitude
  %p
    = f.label  :when
    = f.datetime_select :when
  %p
    = f.label  :title
    = f.text_field :title
  %p
    = f.label  :description
    %br/
    = f.text_area :description, rows: 3
  %p
    - if incident.new_record? == true
      = f.submit "Create"
    - else
      = f.submit "Update"

app/views/incidents/_new.html.haml
%h1 New Incident
= render partial: "my", locals: {incident: incident}

app/views/incidents/_show.html.haml
%p#notice= notice
%p
  %strong Mountain:
  = incident.mountain
%p
  %strong When:
  = incident.when
%p
  %strong Title:
  = incident.title
%p
  %strong Description:
  = incident.description
= link_to 'Edit', edit_incident_path(@incident), remote: true
= link_to 'Back', incidents_path

%script
  document.getElementById("map_info").children.map.hide();

app/views/incidents/create.js.erb
jQuery(function($){
  $('#map_info').html("<%= escape_javascript render(partial: 'show', locals: {incident: @incident}) %>")
})

app/views/incidents/edit.html.haml
%h1 Editing incident
= render 'form'
= link_to 'Show', @incident
|
\#{link_to 'Back', incidents_path}

app/views/incidents/edit.js.erb
jQuery(function($){
  $('#map_info').html("<%= escape_javascript render( partial: 'edit', locals: { incident: @incident }) %>")
})

app/views/incidents/index.html.haml
%h1 Listing incidents
= render partial: "map", locals: { data: "incidents.xml"}, full_page: true, show_action: 'show', new_action: 'new'

app/views/incidents/new.html.haml
%h1 New incident
= render 'form'
= link_to 'Back', incidents_path

app/views/incidents/show.html.haml
%p#notice= notice
%p
  %strong Mountain:
  = @incident.mountain
%p
  %strong Latitude:
  = @incident.latitude
%p
  %strong Longitude:
  = @incident.longitude
%p
  %strong When:
  = @incident.when
%p
  %strong Title:
  = @incident.title
%p
  %strong Description:
  = @incident.description
= link_to 'Edit', edit_incident_path(@incident), remote: true

app/views/incidents/update.js.erb
jQuery(function($){
  $('#map_info').html("<%= escape_javascript render(partial: 'show', locals: {incident: @incident})%>")
});

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Climber</title>
  <%#= javascript_include_tag 'prototype'%>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= auto_discovery_link_tag(:rss, {:action=>'news'}) %>

</head>
<body>

<%= yield %>

</body>
</html>